<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>VideoCall.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VideoCall.Shared\VideoCall.Shared.csproj" />
    <Compile Remove="Server.cs" />
    <Compile Remove="RoomManager.cs" />
    <Compile Remove="CallManager.cs" />
    <Compile Remove="UdpMediaRelay.cs" />
    <Compile Remove="UserManager.cs" />
    <Compile Remove="StartConversationMediaPayload.cs" />
    <Compile Remove="StopConversationMediaPayload.cs" />
  </ItemGroup>

</Project>
